package lk.dce.interview.dto.res;

import lk.dce.interview.dto.ProductDto;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.*;
import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class OrderResDto implements Serializable {
    @Null(message = "Id should be empty. It is auto generated")
    private Integer orderId;
    @NotNull(message = "Order status can not be empty")
    @PositiveOrZero(message = "Invalid order status")
    private Integer orderStatus;
    @NotNull(message = "Order type can not be empty")
    @PositiveOrZero(message = "Invalid order type")
    private Integer orderType;
    @Null(message = "Ordered date is autogenerated")
    private LocalDateTime orderedOn;
    @Null(message = "Shipped date is autogenerated")
    private LocalDateTime shippedOn;
    private Boolean isActive;
    @NotNull(message = "Customer Id must be provided to place the order")
    @PositiveOrZero(message = "Customer Id must be positive")
    private Integer customerId;
    @NotNull(message = "Product id must be provided to place the order")
    private ProductResDto product;

}
