package lk.dce.interview.dto;

import lk.dce.interview.dto.res.OrderResDto;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Null;
import javax.validation.constraints.Pattern;
import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Set;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class CustomerDto implements Serializable {
    @Null(message = "Id should be empty. It is auto generated")
    private Integer userId;
    @NotBlank(message = "User name can't be empty")
    @Pattern(regexp = "^[a-zA-Z]+[0-9]{2}$", message = "Invalid user name")
    private String userName;
    @NotBlank(message = "Email should not be empty")
    @Pattern(regexp = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$", message = "Invalid email")
    private String email;
    @NotBlank(message = "First name can't be empty")
    @Pattern(regexp = "^[A-Za-z ]+$", message = "Invalid first name")
    private String firstName;
    @NotBlank(message = "Last name can't be empty")
    @Pattern(regexp = "^[A-Za-z ]+$", message = "Invalid last name")
    private String lastName;
    @Null(message = "Created date is autogenerated")
    private LocalDateTime createdOn;
    private Boolean isActive;
    @Null(message = "Order set should be empty. It is for the response only")
    private List<OrderResDto> orderList;
}
