package lk.dce.interview.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Column;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Null;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Positive;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class SupplierDto implements Serializable {
    @Null(message = "Id should be empty. It is auto generated")
    private Integer supplierId;
    @NotBlank(message = "Supplier name can't be empty")
    @Pattern(regexp = "^[A-Za-z]+$", message = "Invalid supplier name")
    private String supplierName;
    @Null(message = "Created date is autogenerated")
    private LocalDateTime createdOn;
    @Column(nullable = false, name = "is_active")
    private Boolean isActive;
}
